name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0' # Replace with the desired Flutter version
          architecture: x64

      - name: Get dependencies
        run: flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: ios

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign || exit 1

      - name: Create Payload Directory
        run: mkdir -p build/ios/iphoneos/Payload

      - name: Move Runner.app to Payload
        run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload

      - name: Zip Output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
